### PR TITLE
Fix class generating code to work on Windows

### PR DESCRIPTION
**Pull request by kanei**
On Windows, generating class fails because of the C:\ in the file path. After I've fixed that, it still failed on & which was present in my path, so I've decided it might be best to use the regexp as is listed on the PHP documentation page ([here](http://php.net/manual/en/language.oop5.basic.php))

### CODE REVIEW

**Comment by renebakx** [comment]
Sorry for the late response. I need to test this merge first, the new construction with the static cache needs to be tested not only on windows but under a linux based system as well.

**Comment by kanei** [comment]
Of course. I've been using the code for last 17 days and it's been working fine so far, so on Windows, there should be no trouble.

**Comment by kanei** [comment]
Of course. I've been using the code for last 17 days and it's been working fine so far, so on Windows, there should be no trouble.

**Comment by kanei** [comment]
Of course. I've been using the code for last 17 days and it's been working fine so far, so on Windows, there should be no trouble.

**Comment by drupol** [comment]
This has solved our issues running TFD7 on Windows machines. Thanks!

**Comment by drupol** [comment]
Hi,

I will commit this code in 7.x-3.x on drupal.org repo.

@kanei, you should rebase your pull request against the 3.x branch (or 7.x-3.0-dev).

**Comment by drupol** [comment]
Fixed in 7.x-3.x: http://cgit.drupalcode.org/tfd7/commit/?id=215a6d7263cae210bdc628c81b464b41c9fb7b32

**Comment by drupol** [comment]
The Drupal.org repository is most up to date, please test the 7.x-3.x branch and give feedback.

You can also install this module: https://github.com/drupol/tfd7configuration and test.

**Pull request closed without merging**
